### ISSUE TITLE
Login page custom message above username

### ISSUE THREAD

**Issue by jarrah31** [bugy/script-server#481]
Would it be possible to have a conf.json option to specify a short message within the username/password logon page please?

At the moment I can do a very simple edit on the login.html file to produce what I need, but it would be better if there was an official way to specify a message in the server config file.

My use case is to inform the user which type of credentials they should use to log into script server.

Thanks.

**Comment by bugy** [comment]
Hi @jarrah31 I won't be able to implement it. Do you want to try to create a PR for it?

**Comment by erpheus** [comment]
I have been able to implement this using the theming functionality, by adding the following to my theme.css:

```css
/* Hackily add some text to the log-in panel */
#login-panel > .card-image::after {
  content: "Internal Scripts";
  color: black;
  margin: 12px;
  display: block;
  text-align: center;
  font-size: 1.3em;
}
```

Not the best solution but it works without altering the code. Hope this helps :)
